// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsbGfAbtDvgQkJRTud22ccN-vTVDnowy8',
    appId: '1:195941919654:web:5e2da55f4a393a66d3fd67',
    messagingSenderId: '195941919654',
    projectId: 'kdclpm',
    authDomain: 'kdclpm.firebaseapp.com',
    storageBucket: 'kdclpm.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6RYa68rUoRIQHWn3JeYtubQngx1SGZds',
    appId: '1:195941919654:android:d6c52f36ad1de5f6d3fd67',
    messagingSenderId: '195941919654',
    projectId: 'kdclpm',
    storageBucket: 'kdclpm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBskviBakadQlVA-qELW28dkrFeEsQ492I',
    appId: '1:195941919654:ios:4955cc5bc689fa00d3fd67',
    messagingSenderId: '195941919654',
    projectId: 'kdclpm',
    storageBucket: 'kdclpm.firebasestorage.app',
    iosBundleId: 'com.example.studentManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBskviBakadQlVA-qELW28dkrFeEsQ492I',
    appId: '1:195941919654:ios:4955cc5bc689fa00d3fd67',
    messagingSenderId: '195941919654',
    projectId: 'kdclpm',
    storageBucket: 'kdclpm.firebasestorage.app',
    iosBundleId: 'com.example.studentManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsbGfAbtDvgQkJRTud22ccN-vTVDnowy8',
    appId: '1:195941919654:web:68b797516a6f16fbd3fd67',
    messagingSenderId: '195941919654',
    projectId: 'kdclpm',
    authDomain: 'kdclpm.firebaseapp.com',
    storageBucket: 'kdclpm.firebasestorage.app',
  );
}
